name: Multicoder Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "requirements.txt not found, skipping"

      - name: Build Multicoder EXE
        run: |
          pip install pyinstaller
          pyinstaller --onefile multicoder_gui.py --name Multicoder

      - name: Archive build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Multicoder-EXE
          path: dist/Multicoder.exe

      - name: Show build log
        run: |
          dir dist
          echo "Build complete. Download .exe from GitHub Actions artifacts."
